plugins {
    alias(libs.plugins.android.application)
}

import java.util.Properties
import java.io.FileInputStream

def keystoreProperties = new Properties()

def keystorePropertiesFile =
        rootProject.file("key.properties")

if (keystorePropertiesFile.exists()) {

    keystoreProperties.load(
            new FileInputStream(
                    keystorePropertiesFile
            )
    )
}

android {

    signingConfigs {

        release {

            keyAlias keystoreProperties['keyAlias']

            keyPassword keystoreProperties['keyPassword']

            storeFile file(
                    keystoreProperties['storeFile']
            )

            storePassword keystoreProperties['storePassword']
        }
    }


    namespace = 'com.prajjwals.droidchitect'
    compileSdk 36

    defaultConfig {
        applicationId "com.prajjwals.droidchitect"
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    buildFeatures {
        viewBinding = true
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout
    implementation libs.navigation.fragment
    implementation libs.navigation.ui
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
    implementation 'com.github.ahmmedrejowan:RotaryKnob:0.1'
    implementation 'com.google.code.gson:gson:2.10.1'
}